### ISSUE TITLE
Problem with responsive design

### ISSUE THREAD

**Issue by issacMontes28** [VictorAvelar/cdj#93]
I have to set my browser window in 80% because the match bar doesn't appear complete.

**Comment by VictorAvelar** [comment]
It will be useful to leave a ScreenShoot, just to have it clear :smile:

**Comment by issacMontes28** [comment]
This is the window in full size
![image](https://user-images.githubusercontent.com/28737167/34329416-04038522-e8c5-11e7-9d99-d4225a388e6a.png)


And this is  at 80%
![image](https://user-images.githubusercontent.com/28737167/34329423-26677876-e8c5-11e7-8d51-699308c8c4d9.png)

**Comment by VictorAvelar** [comment]
Just FYI it looks better al 80% jajajaja.

**Comment by VictorAvelar** [comment]
I need to confirm that this problem is solve, @issacMontes28 please check and reply, it should be fixed since #111

**Comment by VictorAvelar** [comment]
Fixed with #111
